name: Build and deploy Angular app to Azure Web App - tfg-front-villar

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/TFG/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: angular-build
          path: .

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'tfg-front-villar'
          slot-name: 'Production'
          package: .